# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
nb_detect_cpp <- function(x, y) {
    .Call(`_nabeatsuR_nb_detect_cpp`, x, y)
}

#' @noRd
nb_count_cpp <- function(x, y) {
    .Call(`_nabeatsuR_nb_count_cpp`, x, y)
}

